### ISSUE TITLE
Error during traning

### ISSUE THREAD

**Issue by Khanwwkkyy** [adept-thu/Dual-Radar#8]
Thank you for your work.
While training is running after the command "python -m pcdet.datasets.dual_radar.dual_radar_dataset_ars548 create_dual_radar_infos tools/cfgs/dataset_configs/dual_radar_dataset_ars548.yaml"  is typed, error's log shows as below:
"train sample_idx: 005052
train sample_idx: 005053
Traceback (most recent call last):
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 507, in <module>
    create_kitti_infos(
  File "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 470, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 210, in get_infos
    return list(infos)
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 140, in process_single_scene
    image_info = {'image_idx': sample_idx, 'image_shape': self.get_image_shape(sample_idx)}
  File "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 81, in get_image_shape
    return np.array(io.imread(img_file).shape[:2], dtype=np.int32)
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/skimage/io/_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 205, in call_plugin
    return func(*args, **kwargs)
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/skimage/io/_plugins/imageio_plugin.py", line 11, in imread
    out = np.asarray(imageio_imread(*args, **kwargs))
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/imageio/v3.py", line 54, in imread
    return np.asarray(img_file.read(**call_kwargs))
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/imageio/plugins/pyav.py", line 444, in read
    frames = np.stack(
  File "<__array_function__ internals>", line 200, in stack
  File "/home/chuhang/miniconda3/envs/Chuhang3_8_16/lib/python3.8/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack"

The error occurs at "/home/chuhang/PycharmProjects/pythonProject/Dual-Radar-master/pcdet/datasets/dual_radar/dual_radar_dataset_ars548.py", line 81, in get_image_shape
    return np.array(io.imread(img_file).shape[:2], dtype=np.int32). Can you help me to analysis it?

BTW training of Lidar and arbe have a same problem at image index-005053.

**Comment by liulin813** [comment]
There is image damage in the first version of the cloud storage data. Please use the cloud storage data again to supplement the images. We apologize for any inconvenience caused

**Comment by Khanwwkkyy** [comment]
Ok, the mail of dataset-request has been sent to you, can you reply me with the link of the new dataset？
